### ISSUE TITLE
Spelling error in UI

### ISSUE THREAD

**Issue by rfitzhugh** [rubrikinc/graphql-playground#11]
**Expected Behavior**
"Select Your Platform"

**Current Behavior**
"Select Your Platfrom"

**Failure Information**

![Screen Shot 2020-03-26 at 2 32 00 PM](https://user-images.githubusercontent.com/29388592/77699176-215cbc00-6f6f-11ea-915a-0b38898e3a92.png)

**Comment by drew-russell** [comment]
Fixed in v1.0.2 release
